wedding-planner-website/config/routes.rb
Rails.application.routes.draw do


  resources :sessions, only: [:new,:create,:destroy]
  get 'gallery_items/index'

  get 'welcome/index'

  get 'users/create'

  get 'users/new'

  get 'welcome/aboutus' => 'welcome#aboutus'

  get 'welcome/contact' => 'welcome#contact'

  get 'welcome/weddingplanner' => 'welcome#weddingplanner'

  get 'welcome/weddingservices' => 'welcome#weddingservices'

  get 'gallery_items/index' => 'gallery_items#index'

  

  get 'posts/index' => 'posts#index'


  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users 
  resources :posts

end

wedding-planner-website/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wedding-planner-website/app/models/gallery_item.rb
class GalleryItem < ApplicationRecord
end

wedding-planner-website/app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true, length: {minimum:3}
	validates :description, presence: true, length: {minimum:1000}
	validates :image_url, presence: true, length: {minimum:3}
end

wedding-planner-website/app/models/session.rb
class Session < ApplicationRecord
end

wedding-planner-website/app/models/user.rb
class User < ApplicationRecord

	validates :mail, presence: true, length: {minimum:5}, uniqueness: true
	validates :password, presence: true, length: {minimum:5}
	validates_format_of :mail, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

	has_secure_password
end

wedding-planner-website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

wedding-planner-website/app/controllers/gallery_items_controller.rb
class GalleryItemsController < ApplicationController
  def index
  	@gallery_items=GalleryItem.paginate(:page => params[:page], :per_page => 6)
  end
end

wedding-planner-website/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts=Post.paginate(:page => params[:page], :per_page => 6)
  end

  def show
  	@post=Post.find(params[:id])
  end

  def update
  end

  def create
    @post=Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
         flash[:error]="Niste unijeli sve podatke ispravno"
         redirect_to new_post_path
      

end
  end

  def new
    	@post=Post.new
    end

  def edit
    	@post=Post.find(params[:id])
  end

  def destroy
		@post=Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
  end

  private

  def post_params
    	params.require(:post).permit(:title,:description,:image_url)
  end
end

wedding-planner-website/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper 
  
  def new
  end

  def create
  	user=User.find_by_mail(params[:mail])
  	if user and user.authenticate(params[:password])
  		session[:user_id]=user.id
  		session[:mail]=user.mail
  		flash[:error]='Logovani ste'
  		redirect_to root_path
  	else
      flash[:error]='Pogresna username/password kombinacija'
      redirect_to new_session_path

  	end
  end

  def destroy
  	session[:user_id]=nil
  	session[:mail]=nil
  	sign_out
  	redirect_to new_session_path, notice: "Odjavljeni ste."
  end

end

wedding-planner-website/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to users_path
  	else
  		redirect_to new_user_path
  	end
  end

  def new
  	@user = User.new
  end

  private

  def user_params
  	params.require(:user).permit(:mail,:password,:password_confirmation)
  end

end

wedding-planner-website/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

wedding-planner-website/app/helpers/application_helper.rb
module ApplicationHelper

end

wedding-planner-website/app/helpers/gallery_items_helper.rb
module GalleryItemsHelper
end

wedding-planner-website/app/helpers/posts_helper.rb
module PostsHelper
end

wedding-planner-website/app/helpers/sessions_helper.rb
module SessionsHelper
	

    def current_user=(user)
    	@current_user=user
    end


    def current_user
        @current_user||=User.find(session[:user_id])   unless session[:user_id]==nil
    end

	def sign_in(user)
		self.current_user=user
	end

	def sign_out
		self.current_user=nil
	end

	def signed_in?
		!self.current_user.nil?
	end
end

wedding-planner-website/app/helpers/users_helper.rb
module UsersHelper
end

wedding-planner-website/app/helpers/welcome_helper.rb
module WelcomeHelper
end

wedding-planner-website/app/views/gallery_items/index.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">GALERIJA:
                <hr>
                <h5 class="page-podheader">Dio nasih prica</h5>
                <hr>
            </h3>

            <div class="col-md-12">
                  
				<div class="row">
					<% @gallery_items.each do |p|%>

					<div class="card zoom" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
					  <img class="card-img-top" src="<%=p.image_url %>" alt="Card image cap">
					  <div class="card-body">
					    <h5 class="card-title"><%= p.title %></h5>
					    <p class="card-text"><%= p.description %></p>
					    
					  </div>
					</div>
                            
                    <% end %>			


				</div>
			</div>
      </div>
</div>

<div class="pager-justify">
	
    <%= will_paginate @gallery_items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , :previous_label => "&laquo; Prethodna",:next_label => "Sljedeca &raquo;"%>
</div>



</div>

wedding-planner-website/app/views/layouts/_navigacija.html.erb
<ul class="nav justify-content-center">
  <li class="nav-item">
    <a class="nav-link active" href="/welcome/index" >POCETNA</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/welcome/aboutus" >O NAMA</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/gallery_items/index" >GALERIJA</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/welcome/contact" >KONTAKT</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="/posts/index">BLOG</a>
  </li>

   <% if signed_in? %>
         
          <li class="nav-item"><%= link_to "ODJAVA", session_path(current_user), class: "nav-link", method: "delete" %></li>
  <% end %>
</ul>

wedding-planner-website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddingPlannerWebsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navigacija' %>
  	
    <%= yield %>
    
  </body>
</html>

wedding-planner-website/app/views/posts/_form.html.erb
<div class="col-md-12 col-md-offset-4">
<div class="registracija-forma">

    <%= form_for @post,url: posts_path do |u| %>
          
            <div class="form-group page-podheader-input">
            <%= u.label :title,"Naslov blog posta:"%><br/>
            <%= u.text_field :title, class:"form-control",placeholder: 'Unesite naziv post-a' %><br/>
            </div>

            <div class="form-group page-podheader-input">
            <%= u.label :image_url,"Link slike:"%><br/>
            <%= u.text_field :image_url, class:"form-control", placeholder: 'Preporucuje se slika velicine 1000px x 720px'%><br/>
            </div>


            <div class="form-group page-podheader-input">
            <%= u.label :description,"Opis blog posta:"%><br/>
            <%= u.text_area:description, class:"form-control", placeholder:'Unesite tekst minimalne duzine 1000 karaktera' %><br/>
            </div>


          

          <p>
            <input style="width: 100%;" type="submit" class="btn btn-default dugme-post" value="Dodaj post">
            
          </p>
          
    <% end %>

</div>
</div>

wedding-planner-website/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

wedding-planner-website/app/views/posts/index.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">BLOG POSTOVI:
                <hr>
                <h5 class="page-podheader">Vjencanja kroz postove...
                <% if signed_in? %>
                <a href="<%=new_post_path%>" style="float:right; margin-right: 5%; ">
                        <button class="btn btn-default btn-space dugme-post" >Dodaj novi</button>
				    </a></h5>
				 <% end %>
                <hr>
            </h3>

            <div class="col-md-12">
                  
				<div class="row">
					<% @posts.each do |p|%>

					<div class="card zoom" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
					  <img class="card-img-top" src="<%=p.image_url %>" alt="Card image cap">
					  <div class="card-body">
					    <h5 class="card-title"><%= p.title %></h5>
					    <p class="card-text"><%= p.description[0..200].gsub(/\s\w+\s*$/,'...') %></p>
                        
                        <div class="row">
                        	<a href="<%=post_path(p.id)%>" >
                            <button class="btn btn-default btn-space dugme-post" id="dugme_<%= p.id %>">Prikazi vise</button>
							</a>

                            <% if signed_in? %>
							<div class="dugme-delete" >
							<%= link_to 'Obrisi', post_path(p.id), method: :delete, data: { confirm: 'Jeste li sigurni da zelite obrisati post?' }, :style => 'color:white;'%>
                            
                        	</div>
                        	<% end %>
                        </div>
					    
					    
					  </div>
					</div>
                            
                    <% end %>			


				</div>

				
			</div>
      </div>
</div>

<div class="pager-justify">
	
    <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer , :previous_label => "&laquo; Prethodna",:next_label => "Sljedeca &raquo;"%>
</div>



</div>

wedding-planner-website/app/views/posts/new.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">DODAVANJE POSTA:
                <hr>
                <h5 class="page-podheader">Forma za unos posta...</h5>
                <hr>
            </h3>
      </div>
</div>
  <% if flash[:error] %>

      <div class="alert alert-danger">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= flash[:error] %>
    </div>
 
 <% end %>
<%= render 'form'%>

</div>

wedding-planner-website/app/views/posts/show.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">BLOG POST:
                <hr>
                <h5 class="page-podheader">O vjencanjima...</h5>
                <hr>
            </h3>
      </div>
</div>

<div class="row">

 <div class="col-md-6" >
      <div class="row vdivide" >
          <%= image_tag("#{@post.image_url}", :alt => "rings photo",  :class => "pic-aboutus") %>
      </div>  
</div>

 <div class="col-md-6" >
 	<h1 class="blog-text"><%= @post.title %></h1>
 	<p class="aboutus-text"><%= @post.description %></p>
 </div>

</div>

wedding-planner-website/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

wedding-planner-website/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

wedding-planner-website/app/views/users/new.html.erb
<h2 class="naslov"> Registracija </h2> <br>
  <% if flash[:error] %>
  <% flash[:error].each do |o| %>
      <div class="alert alert-danger">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%= o %>
    </div>
  <% end %>
 <% end %>
<%= render 'form'%>

wedding-planner-website/app/views/welcome/aboutus.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">O NAMA:
                <hr>
                <h5 class="page-podheader">Ko smo mi?</h5>
                <hr>
            </h3>
      </div>
</div>

<div class="row">

 <div class="col-md-6">
      
      
        <%= image_tag("rings.jpg", :alt => "rings photo",  :class => "pic-aboutus") %>
      
    
        
</div>

 <div class="col-md-6" >
 	<p class="aboutus-text">Mi smo grupa mladih entuzijasta zaljubljenih u sretne i nezaboravne trenutke Vaseg zivota. <br/>
 	Prvo vjencanje organizovali smo i planirali prije vise od <b><i> 5 godina</i></b>, a nas tim predano radi kako na licnom tako i na profesinalnom usavrsavanju kako bismo Vam ponudili samo najbolje.
 	Organizovali smo preko <b><i>120 slavlja </i></b> i bili dijelom neizmjerne srece i zadovoljstva nasih klijenta.
 	Mi planiramo, dizajniramo, uredjujemo i upravljamo slavljima sirom svijeta. Od malih, intimnih okupljanja do velikih raskosnih dogadjaja, nasa vjencanja i zabave su nezaboravna, magicna iskustva, savrseno isplanirana i predivno realizovana.</p>
 </div>

</div>

<div class="row">
	<p class="aboutus-text">
		Kao rezultat dugogodisnjeg iskustva nastale su i dvije knjige o vjencanjima koje su za kratko vrijeme postale jedne od najcitanjih iz oblasti organizovanja vjencanja.
		Takodjer, ponosni smo sto smo bili dijelom <b><i> kraljevskog</i> </b> vjencanja <b><i>princa Williama </i></b> i <b><i> Kate Middleton</i></b>. 
	</p>
	
</div>

wedding-planner-website/app/views/welcome/contact.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">KONTAKT:
                <hr>
                <h5 class="page-podheader">Kontaktirajte nas</h5>
                <hr>
            </h3>
      </div>
</div>

<div class="row">

   <div class="col-md-6">
      <div class="row vdivide">
          
        <div id="googleMap" style="width:100%;height:400px;border: 
        2px dotted #9c886b; border-radius: 2px;"></div>

      </div>  
  </div>


 <div class="col-md-6">
      <div class="row vdivide">
        <p class="contact-text">
          <b>
          SARAJEVO EFSA WEDDING & PARTY PLANNING
          </b>
          <br><br>

          <b><i>Telefon:</i></b> +378 33 225 883
          <br>
          <b><i>E-mail:</i></b> info@sarajevoefsa.ba
          <br><br>

          <b>Dizajn i dekoracije kontakt:</b>
          <br/><br/>
          <b><i>Telefon:</i></b> +378 33 225 885
          <br>
          <b><i>E-mail:</i></b> dd@sarajevoefsa.

          <br><br>

          <b>Kreacije kontakt:</b>
          <br/><br/>
          <b><i>Telefon:</i></b> +378 33 225 886
          <br>
          <b><i>E-mail:</i></b> create@sarajevoefsa.ba
          <br><br>
          <b>
            <i>Posjetite nas:<br></i>
          </b>
          
          Trg oslobodjenja Alija Izetbegovic 1, <br>
          71 000 Sarajevo, <br>
          Bosna i Hercegovina

        </p>
        <br>
        
      </div>  
</div>


</div>

<script>
function myMap() {
  var myCenter = new google.maps.LatLng(43.8586393, 18.4247358);
  var mapCanvas = document.getElementById("googleMap");
  var mapOptions = {center: myCenter, zoom: 5};
  var map = new google.maps.Map(mapCanvas, mapOptions);
  var marker = new google.maps.Marker({position:myCenter});
  marker.setMap(map);
}
</script>


<script src="https://maps.googleapis.com/maps/api/js?key=
AIzaSyBe0uCNiQBawMsyik3Sl1jVyu4tjN9Mx3g
&callback=myMap"></script>

wedding-planner-website/app/views/welcome/index.html.erb
<div class="naslovna">

	<%= image_tag("wedding.jpg", :alt => "wedding photo",  :class => "pic") %>

	<div class="buttons">

		<a href="/welcome/weddingplanner">
		<button type="button" class="btn btn-secondary btn-lg dugme">Planer vjencanja</button>
		</a>

		<a href="/welcome/weddingservices">
		<button type="button" class="btn btn-secondary btn-lg dugme">Usluge vjencanja</button>
         </a>

        <% if !signed_in? %> 
			<a href="<%=new_session_path%>">
			<button type="button" class="btn btn-secondary btn-lg dugme">Moj racun</button>
		    </a>
	    <% end %>
		
	</div>
	
</div>

<% if !signed_in? %> 
<div id="podnozje"><b >Copyright &copy; EFSA 2017/2018.</b></div>
<% end %>

wedding-planner-website/app/views/welcome/weddingplanner.html.erb
<div class="container tijelo">

<div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header">PLANER VJENCANJA:
                <hr>
                <h5 class="page-podheader">Kako i zasto?</h5>
                <hr>
            </h3>
      </div>
</div>

<div class="row">

  <p class="aboutus-text" >Mi smo grupa mladih entuzijasta zaljubljenih u sretne i nezaboravne trenutke Vaseg zivota. <br/>
  Ukoliko zelite da bezbrizno i sretno docekate i provedete najvazniji dan u Vasem zivotu, 
  dovoljno je da nas kontaktirate, a mi cemo se pobrinuti da sve bude <b>savrseno</b>.
  <br><br>
  <h4 class="page-podheader-input" style="color:#9c886b">
  <b><i>Planer vjencanja ce se u dogovoru sa Vama pobrinuti za:</i></b>
  </h4>
  <br/>
  </p>
</div>


<div class="col-md-12">
        <div class="row">

        <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
            <div class="img-circle">
              <img class="card-img-top" src="http://www.sarahhaywood.com/media/4625/destination-weddings.jpeg?anchor=center&mode=crop&width=320&heightratio=1&format=jpg&quality=90&slimmage=true&rnd=131382894080000000" alt="Card image cap">
            </div>
            
            <div class="card-body">
              
              <h5 class="card-title" style="text-align: center;">DESTINACIJE</h5>
              <hr>
            </div>      
        </div>

          <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
              <div class="img-circle">
                <img class="card-img-top" src="http://www.sarahhaywood.com/media/4529/luxury-party-planners.jpg?anchor=center&mode=crop&width=320&heightratio=1&format=jpg&quality=90&slimmage=true&rnd=131382899020000000" alt="Card image cap">
              </div>
              
              <div class="card-body">
                
                <h5 class="card-title" style="text-align: center;">ZABAVU</h5>
                <hr>
              </div>      
          </div>

          <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
              <div class="img-circle">
                <img class="card-img-top" src="https://assets.vogue.com/photos/589146407edfa70512d634ca/master/pass/02-carl-philip-sofia-of-sweden-royal-weddings-vogue-.jpg" alt="Card image cap">
              </div>
              
              <div class="card-body">
                
                <h5 class="card-title" style="text-align: center;">PROTOKOL</h5>
                <hr>
              </div>      
          </div>
      
      </div>
    
</div>

wedding-planner-website/app/views/welcome/weddingservices.html.erb
<div class="container tijelo">

<div class="row">
      <div class="col-lg-12">
            <h3 class="page-header">USLUGE VJENCANJA:
                <hr>
                <h5 class="page-podheader">Nudimo Vam...</h5>
                <hr>
            </h3>
      </div>
</div>

<div class="row">

  <p class="aboutus-text" > Vec <b><i>5 godina</i></b> nastojimo da Vam ponudimo samo najbolje. Svakodnevno pratimo svjetske trendove i trudimo se da i sami kreiramo nove.
  <br><br>
  <h4 class="page-podheader-input" style="color:#9c886b">
  <b><i>Trenutno nase ponude obuhvataju:</i></b>
  </h4>
  <br/>
  </p>
</div>


<div class="col-md-12">
        <div class="row">

        <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
            <div class="img-circle">
              <img class="card-img-top" src="https://i.pinimg.com/originals/e5/7d/bb/e57dbbe1f0ee95c5b8491231896b3d97.jpg" alt="Card image cap">
            </div>
            
            <div class="card-body">
              
              <h5 class="card-title" style="text-align: center;">WEB STRANICU VJENCANJA</h5>
              <hr>
            </div>      
        </div>


        <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
            <div class="img-circle">
              <img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuIU7goS9MwfN5RwI1cZpW114fd9wZEpdqwr4tN-sg5hHVIqaMag" alt="Card image cap">
            </div>
            
            <div class="card-body">
              
              <h5 class="card-title" style="text-align: center;">PRIPREMA DESTINACIJE</h5>
              <hr>
            </div>      
        </div>

          <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
              <div class="img-circle">
                <img class="card-img-top" src="http://www.sarahhaywood.com/media/4529/luxury-party-planners.jpg?anchor=center&mode=crop&width=320&heightratio=1&format=jpg&quality=90&slimmage=true&rnd=131382899020000000" alt="Card image cap">
              </div>
              
              <div class="card-body">
                
                <h5 class="card-title" style="text-align: center;">ZABAVU</h5>
                <hr>
              </div>      
          </div>

         <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
                      <div class="img-circle">
                        <img class="card-img-top" src=" https://images.trvl-media.com/hotels/13000000/12070000/12064300/12064223/83dfe8d8_z.jpg">
                      </div>
                      
                      <div class="card-body">
                        
                        <h5 class="card-title" style="text-align: center;">FOTOGRAFISANJE</h5>
                        <hr>
                      </div>      
                  </div>


         

        
         
        <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; ">
          <div class="img-circle">
            <img class="card-img-top" src="http://www.sarahhaywood.com/media/2117/wedding-bible-wedding-book-sarah-haywood.jpg?anchor=center&mode=crop&width=320&heightratio=1&format=jpg&quality=90&slimmage=true&rnd=130887277770000000" alt="Card image cap">
          </div>
          
          <div class="card-body">
            
            <h5 class="card-title" style="text-align: center;">KNJIGU VJENCANJA</h5>
            <hr>
               
          </div>

        </div>

        <div class="card zoom circle" style="width: 20rem; margin-right: 4%; margin-top:10px; margin: auto;">

              <div class="img-circle">
                <img class="card-img-top" src="http://www.sarahhaywood.com/media/1240/workshop.jpg?anchor=center&mode=crop&width=320&heightratio=1&format=jpg&quality=90&slimmage=true&rnd=130837914240000000" alt="Card image cap">
              </div>
              
              <div class="card-body">
                
                <h5 class="card-title" style="text-align: center;">KURSEVE ZA DOGADJAJ</h5>
                <hr>
              </div>      
        </div>
      </div>
    
</div>